name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (no publish)'
        type: boolean
        default: false

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version_changed: ${{ steps.check.outputs.version_changed }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
      - name: Check version changes
        id: check
        run: |
          LOCAL_VERSION=$(node -p "require('./package.json').version")
          echo "Local version: $LOCAL_VERSION"

          NPM_VERSION=$(npm view merkletreejs version 2>/dev/null || echo "0.0.0")
          echo "NPM version: $NPM_VERSION"

          if [ "$LOCAL_VERSION" != "$NPM_VERSION" ]; then
            echo "Version changed from $NPM_VERSION to $LOCAL_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
            echo "version=$LOCAL_VERSION" >> $GITHUB_OUTPUT
          else
            echo "Version unchanged ($LOCAL_VERSION)"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          fi

  publish-npm:
    needs: check-version
    if: needs.check-version.outputs.version_changed == 'true' && !github.event.inputs.dry_run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - name: Publish to NPM
        run: |
          if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
            echo "DRY RUN: Would publish to npm"
            npm publish --dry-run
          else
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-release:
    needs: [check-version, publish-npm]
    if: needs.check-version.outputs.version_changed == 'true' && !github.event.inputs.dry_run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release Archive
        run: |
          zip -r release.zip . -x ".git/*" ".github/*" "node_modules/*"
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ needs.check-version.outputs.version }}
          name: Release v${{ needs.check-version.outputs.version }}
          body: |
            Version: ${{ needs.check-version.outputs.version }}
            Commit: ${{ env.COMMIT_HASH }}

            📦 NPM Package: https://www.npmjs.com/package/merkletreejs

            This release was automatically generated by GitHub Actions.
          files: |
            release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
